/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_control;

import Nodos.Arbol;
import file_control.Jason;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author German David
 */
public class ChooserFrame extends javax.swing.JFrame {

    JFrame frame;
    File users, posts, comments;
    Jason jason;
    Arbol arbol;
    /**
     * Creates new form ChooserFrame
     * @param frame
     */
    public ChooserFrame(JFrame frame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.frame = frame;
        escogeC.setContentAreaFilled(false);
        escogeU.setContentAreaFilled(false);
        escogeP.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jason = new Jason();
        //chooser = new ChooserFrame(this);
        arbol = new Arbol();
        
        users = new File("C:\\Users\\German David\\Desktop\\user.txt");
        posts = new File("C:\\Users\\German David\\Desktop\\posts.txt");
        comments = new File("C:\\Users\\German David\\Desktop\\comments.txt");
        
    }

        //Este método crea el fileChooser para poder navegar y encontrar los archivos
    private static File createFileChooser(final JFrame frame) {
        
        String filename = File.separator+"tmp";
        //Crea el fileChooser
        JFileChooser fileChooser = new JFileChooser(new File(filename));
        //Establece un FileFilter para que solo se muestre cierto tipo de archivo
        fileChooser.setFileFilter(new FileFilter() {
        @Override
        //Verifica que solo se encuentren archivos txt
        public boolean accept(File f) {
            if (f.isDirectory()) {
                return true;
            }
            final String name = f.getName();
            return name.endsWith(".txt");
        }
        
        //Agrega al descripción para que el usuario sepa que tipo de archivo debe encontrar
        @Override
        public String getDescription() {
            return "*.txt";
        }
    });
        try{
        // Configura el tipo de mensaje para abrir el buscador de archivos
        fileChooser.showOpenDialog(frame);
        
        System.out.println("File to open: " + fileChooser.getSelectedFile());
        return fileChooser.getSelectedFile();
        }catch(NullPointerException io){
            System.out.println("El proceso fue cancelado, ingrese nuevamente el archivo");
            return null;
        }
        
        /*
        // pop up an "Save File" file chooser dialog
        fileChooser.showSaveDialog(frame);
 
        System.out.println("File to save: " + fileChooser.getSelectedFile());
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        escogeU = new javax.swing.JButton();
        escogeP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        escogeC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setColumns(20);
        text.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        text.setRows(5);
        text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        text.setEnabled(false);
        scroll.setViewportView(text);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 600, 500));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 195, 24));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arcAmarillo.png"))); // NOI18N
        jButton2.setText("Convertir");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 195, 24));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 30));

        escogeU.setBackground(new java.awt.Color(0, 102, 204));
        escogeU.setFont(new java.awt.Font("Dubai Light", 1, 28)); // NOI18N
        escogeU.setForeground(new java.awt.Color(255, 255, 255));
        escogeU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seleccionar.png"))); // NOI18N
        escogeU.setText("Escoger");
        escogeU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escogeU.setOpaque(false);
        escogeU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogeUActionPerformed(evt);
            }
        });
        getContentPane().add(escogeU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 80));

        escogeP.setBackground(new java.awt.Color(255, 255, 255));
        escogeP.setFont(new java.awt.Font("Dubai Light", 1, 28)); // NOI18N
        escogeP.setForeground(new java.awt.Color(255, 255, 255));
        escogeP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seleccionar.png"))); // NOI18N
        escogeP.setText("Escoger");
        escogeP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escogeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogePActionPerformed(evt);
            }
        });
        getContentPane().add(escogeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 80));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 195, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Posts");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 30));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 195, 24));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comentarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 300, 30));

        escogeC.setBackground(new java.awt.Color(255, 255, 255));
        escogeC.setFont(new java.awt.Font("Dubai Light", 1, 28)); // NOI18N
        escogeC.setForeground(new java.awt.Color(255, 255, 255));
        escogeC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seleccionar.png"))); // NOI18N
        escogeC.setText("Escoger");
        escogeC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escogeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogeCActionPerformed(evt);
            }
        });
        getContentPane().add(escogeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 300, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escogeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogeCActionPerformed
        //BufferedReader para poder convertir el archivo a String
        BufferedReader br;
        text.setText("");
        try {
            //Crea el bufferedReader y le agrega un fileReader que leerá el archivo seleccionado
            comments = createFileChooser(this);
            br = new BufferedReader(new FileReader(comments));
            String st;
            while ((st = br.readLine()) != null)
            text.append(st+"\n");
            //Catchs para los dos tipos de excepciones que podríamos encontrar
        } catch (FileNotFoundException ex) {
            System.out.println("Este archivo no pudo ser leido");;
        } catch (NullPointerException ex) {
            System.out.println("Ha sucedido un error");;
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(comments!=null){
            escogeC.setText(comments.getName());
        }else{
            escogeC.setText("Escoger");
        }

    }//GEN-LAST:event_escogeCActionPerformed

    private void escogePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogePActionPerformed
        //BufferedReader para poder convertir el archivo a String
        BufferedReader br;
        text.setText("");
        try {
            //Crea el bufferedReader y le agrega un fileReader que leerá el archivo seleccionado
            posts = createFileChooser(this);
            br = new BufferedReader(new FileReader(posts));
            String st;
            while ((st = br.readLine()) != null)
            text.append(st+"\n");
            //Catchs para los dos tipos de excepciones que podríamos encontrar
        } catch (FileNotFoundException ex) {
            System.out.println("Este archivo no pudo ser leido");;
        } catch (NullPointerException ex) {
            System.out.println("Ha sucedido un error");;
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(posts!=null){
            escogeP.setText(posts.getName());
        }else{
            escogeP.setText("Escoger");
        }
    }//GEN-LAST:event_escogePActionPerformed

    private void escogeUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogeUActionPerformed
        //BufferedReader para poder convertir el archivo a String
        BufferedReader br;
        text.setText("");
        try {
            //Crea el bufferedReader y le agrega un fileReader que leerá el archivo seleccionado
            users = createFileChooser(this);
            br = new BufferedReader(new FileReader(users));
            String st;
            while ((st = br.readLine()) != null)
            text.append(st+"\n");
            //Catchs para los dos tipos de excepciones que podríamos encontrar
        } catch (FileNotFoundException ex) {
            System.out.println("Este archivo no pudo ser leido");;
        } catch (NullPointerException ex) {
            System.out.println("Ha sucedido un error");;
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(users!=null){
            escogeU.setText(users.getName());
        }else{
            escogeU.setText("Escoger");
        }
    }//GEN-LAST:event_escogeUActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(users == null || comments == null || posts == null){
            JOptionPane.showMessageDialog(this, "No se ha ingresado archivo");
        }else{
            try {
                arbol = jason.convert(arbol,users, posts, comments);
                arbol.showTree();
                Blog b = new Blog(arbol, this);
                this.setVisible(false);
                b.setVisible(true);

            } catch (IOException ex) {
                Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public JFrame getFrame() {
        return frame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escogeC;
    private javax.swing.JButton escogeP;
    private javax.swing.JButton escogeU;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
