/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_control;

import Nodos.Arbol;


/**
 * Se muestra el post de determinado usuario, con sus comentarios. Además se muestra parte de la información del usuario
 * 
 */
public class FeedUsuario extends javax.swing.JFrame {

    static infoPage tutor;
    perfilUsuario perfil;
    ArbolPanel panel;
    Arbol a;
    public FeedUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atras = new javax.swing.JButton();
        buscarUsuario = new javax.swing.JButton();
        buscarPosts = new javax.swing.JButton();
        tutorial = new javax.swing.JButton();
        perfilUsuario = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 57, 66));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/atrasFeed.png"))); // NOI18N
        atras.setBorder(null);
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscarUsuarios.png"))); // NOI18N
        buscarUsuario.setBorder(null);
        buscarUsuario.setBorderPainted(false);
        buscarUsuario.setContentAreaFilled(false);
        buscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, -1));

        buscarPosts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscarPublicacion.png"))); // NOI18N
        buscarPosts.setBorder(null);
        buscarPosts.setBorderPainted(false);
        buscarPosts.setContentAreaFilled(false);
        buscarPosts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarPosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPostsActionPerformed(evt);
            }
        });
        getContentPane().add(buscarPosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 60));

        tutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tutAmarillo.png"))); // NOI18N
        tutorial.setBorder(null);
        tutorial.setBorderPainted(false);
        tutorial.setContentAreaFilled(false);
        tutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialActionPerformed(evt);
            }
        });
        getContentPane().add(tutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 60));

        perfilUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuarios.png"))); // NOI18N
        perfilUsuario.setBorderPainted(false);
        perfilUsuario.setContentAreaFilled(false);
        perfilUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(perfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 120, 120));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondofeedUsuario.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed
    /**
    * Botón para hacer la búsqueda del usuario
    * @param evt 
    */
    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsuarioActionPerformed
    /**
    * 
    * @param evt 
    */
    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        tutor.setVisible(true);
        tutor.run();
        this.setVisible(false);
    }//GEN-LAST:event_tutorialActionPerformed

    private void perfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilUsuarioActionPerformed
        perfil.setVisible(true);
    }//GEN-LAST:event_perfilUsuarioActionPerformed

    private void buscarPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPostsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPostsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton atras;
    private javax.swing.JButton buscarPosts;
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JButton perfilUsuario;
    private javax.swing.JButton tutorial;
    // End of variables declaration//GEN-END:variables
}
