/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_control;

import Atributos.Lista;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 * Clase donde se muestra el tutorial para el usuario.
 */
public class infoPage extends javax.swing.JFrame {

    BufferedImage[] generalL;
    BufferedImage[] principalL;
    BufferedImage[] guardado;
    BufferedImage[] blog;
    BufferedImage[] arbol;
    int actual;
    JFrame frame;
    Graphics g;
    
    public infoPage(JFrame Frame) throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tutorial");
        this.setResizable(false);
        actual = 0;
        frame = Frame;
        general.setBackground(Color.BLUE);
        generalL = new BufferedImage[5];
        generalL = fill(generalL);
        g = panel.getGraphics();  
        g.drawImage(generalL[actual], 0, 0,panel.getWidth(),panel.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void run(){
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        general = new javax.swing.JButton();
        principal = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        der = new javax.swing.JButton();
        izq = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        general.setBackground(new java.awt.Color(0, 102, 153));
        general.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        general.setForeground(new java.awt.Color(255, 255, 255));
        general.setText("General");
        general.setBorder(null);
        general.setBorderPainted(false);
        general.setContentAreaFilled(false);
        general.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalActionPerformed(evt);
            }
        });
        getContentPane().add(general, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        principal.setBackground(new java.awt.Color(0, 102, 153));
        principal.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        principal.setForeground(new java.awt.Color(255, 255, 255));
        principal.setText("Principal");
        principal.setBorder(null);
        principal.setBorderPainted(false);
        principal.setContentAreaFilled(false);
        principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });
        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salvar.png"))); // NOI18N
        jButton3.setText("Guardado");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 150, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blog.png"))); // NOI18N
        jButton4.setText("Blog");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 150, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verarbol.png"))); // NOI18N
        jButton5.setText("Arból");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 150, -1));

        panel.setMaximumSize(new java.awt.Dimension(784, 488));
        panel.setOpaque(false);
        panel.setPreferredSize(new java.awt.Dimension(784, 488));

        der.setBackground(new java.awt.Color(0, 102, 153));
        der.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechadr.png"))); // NOI18N
        der.setBorder(null);
        der.setBorderPainted(false);
        der.setContentAreaFilled(false);
        der.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });

        izq.setBackground(new java.awt.Color(0, 102, 153));
        izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaiz.png"))); // NOI18N
        izq.setBorder(null);
        izq.setBorderPainted(false);
        izq.setContentAreaFilled(false);
        izq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(izq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addComponent(der, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(der, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(izq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(251, 255, 241));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/atras2.png"))); // NOI18N
        jButton6.setText("Atrás");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalActionPerformed
        actual = 0;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_generalActionPerformed

    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        actual = 1;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_principalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actual = 2;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        actual = 3;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        actual = 4;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        this.frame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed
        if(actual<generalL.length-1)
        actual++;
        else
        actual = 0;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_derActionPerformed

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        if(actual>0)
        actual--;
        else
        actual = generalL.length-1;
        g.drawImage(generalL[actual], 0,0,panel.getWidth(),panel.getHeight() ,this);
    }//GEN-LAST:event_izqActionPerformed

    public void setFrame(JFrame frame){
        this.frame=frame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton der;
    private javax.swing.JButton general;
    private javax.swing.JButton izq;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton principal;
    // End of variables declaration//GEN-END:variables

    private BufferedImage[] fill(BufferedImage[] generalL) throws IOException {
        for (int i = 0; i < generalL.length; i++) {
            generalL[i] = ImageIO.read(getClass().getResource("/Images/tutorial"+(i+1)+".png"));
        }
        return generalL;
    }
}
